chat:
  format: "%vault_prefix%  %player_displayname% > {message}"
  tagcolor:
    color: e
    enabled: true
bot:
  token: ""
  prefix: "!"
  discord-role: "756559569874059295"
  chat-channel: "756570930674794526"